version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test
          
      - store_test_results:
          path: reports/test_report.txt

      - store_artifacts:
          path: reports
          destination: reports/test_artifacts.txt