version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          sudo chown -R circleci:circleci /usr/local/bin
      - run:
          sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
            - /usr/local/bin
            - /usr/local/lib/python3.7/site-packages

          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            python manage.py test lists.tests
          
      - run:
          name: Run functional tests
          command: |
            . venv/bin/activate
            python manage.py test functional_tests

      - store_test_results:
          path: reports/test_report.txt

      - store_artifacts:
          path: reports
          destination: reports/test_artifacts.txt