version: 2
jobs:
  "unit-tests":
    steps:
      - run:
          name: unit tests
          command: |
          . venv/bin/activate
          python manage.py test lists
  
  "functional-tests":
    steps:
      - run:
          name: functional tests
          command: |
          .venv/bin/activate
          python manage.py test functional_tests
workflows:
  version: 2
  build:
    docker:
      - image: circleci/python:3.7.3-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
            - /usr/local/bin
            - /usr/local/lib/python3.7/site-packages

          key: v1-dependencies-{{ checksum "requirements.txt" }}

      jobs:
        - "unit-tests"
        - "functional-tests"

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports
          destination: reports