version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-node-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: set up
          command: |
            sudo chown -R circleci:circleci reports
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
            sudo npm install -g npm@latest
      - restore_cache:
          keys:
            - python-dependencies-{{ checksum "requirements.txt" }}
            - npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
            - /usr/local/bin
            - /usr/local/lib/python3.7/site-packages

          key: python-dependencies-{{ checksum "requirements.txt" }}
          
      - run:
          name: install npm packages
          command: |
            npm install
      - save_cache:
          paths:
            - /node_modules/
          
          key: npm-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            python manage.py test lists.tests
          
      - run:
          name: Run functional tests
          command: |
            . venv/bin/activate
            python manage.py test functional_tests

      - run:
          name: Run linting
          command: |
            . venv/bin/activate
            flake8 --config=tox.ini

      - store_test_results:
          path: reports/test_report.txt

      - store_artifacts:
          path: reports
          destination: reports/test_artifacts.txt